#spring:
#  profiles:
#    active: prod
#---
#spring:
#  profiles:
#    active: dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/sopt_32?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: sopt_server
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace