package com.cds.ohouse.domain;

public enum SubCategoryStatus {
    INDOOR_SUNLIGHT, LEAK, INDOOR_NOISE, DEFAULT_OPTION, HEATING, PET,
    DOORLOCK,
    SINK_DRAIN, SINK_PRESSURE, SINK_STATUS, BURNER_STATUS, KITCHEN_VENTILATOR,
    WALLPAPER, FLOOR, BALCONY,

    BED_ROOM_MOLD, BED_ROOM_NOISE, BED_ROOM_SUNLIGHT,
    WASHSTAND_STATUS, WASHSTAND_DRAIN, WASHSTAND_PRESSURE, BATHROOM_MOLD, TOILET, BATH_ROOM_VENTILATOR, TOWER,
    CCTV, APT_GATE,
    WORN,
    PARKABLE, PARKING_TYPE, PLAYGROUND, ELEVATOR,
    TRAIN_AIRPORT, BUS_STOP, SUBWAY,
    ACADEMY, ELEMENTARY, MIDDLE_HIGH_SCHOOL

}
