package com.cds.ohouse.domain;

public enum SubCategoryStatus {

    DOORLOCK, SHOECABINET, SECONDARYDOOR,

    BED_ROOM_NOISE, BED_ROOM_MOLD, BED_ROOM_SUNLIGHT,

    CCTV, APT_GATE,

    WORN,

    PARKABLE, PARKING_TYPE, PLAYGROUND, ELEVATOR,

    TRAIN_AIRPORT, BUS, SUBWAY,

    PUBLIC_FACILITIES, SUPERMARKET, DINING_OPTIONS, HOSPITAL_PHARMACY,

    PARK_LAKE, SECURITY, HAZARDOUS,

    ACADEMY, ELEMENTARY_SCHOOL, MIDDLE_HIGH_SCHOOL
}
