package com.cds.ohouse.domain;

public enum SubCategoryStatus {

   SUNLIGHT, LEAK, HEATING,

    SINK_DRAIN, SINK_PRESSURE,

    WALLPAPER, FLOOR, BALCONY,

    WASHSTAND_STATUS, WASHSTAND_DRAIN, WASHSTAND_PRESSURE, MOLD, TOILET
}
